use_frameworks!

platform :ios, '9.0'

target 'SupportCarthageSDK_Example' do
  pod 'SupportCarthageSDK', :path => '../'

  target 'SupportCarthageSDK_Tests' do
    inherit! :search_paths

    
  end
end
